### ISSUE TITLE
Compilation error after upgrading to 0.2.5

### ISSUE THREAD

**Issue by tomas789** [shssoichiro/sqlformat-rs#47]
After upgrading to 0.2.5, I'm getting following error. With 0.2.4 everything works as expected.

```
error[E0716]: temporary value dropped while borrowed
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlformat-0.2.5/src/formatter.rs:140:14
    |
139 |         let value = if token.kind == TokenKind::Reserved {
    |             ----- borrow later stored here
140 |             &self.equalize_whitespace(&self.format_reserved_word(token.value))
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ creates a temporary value which is freed while still in use
141 |         } else {
    |         - temporary value is freed at the end of this statement
    |
    = note: consider using a `let` binding to create a longer lived value

```

I'm using Rust 1.76.0. Running on MacBook Pro M1.

Minimal reproducible example (`Dockerfile`)

```
FROM rust:1.76.0-bookworm
RUN cargo install sqlx-cli@0.8.0
```

**Comment by tomas789** [comment]
I'm getting the error because I'm running 

`cargo install sqlx-cli@0.8.0 --no-default-features --features native-tls,postgres`

**Comment by shssoichiro** [comment]
Interesting, this works against the latest Rust compiler, but not against 1.76. But to maintain compatibility, I'll fix this to compile with the older version.

**Comment by tomas789** [comment]
@shssoichiro That would be great! Thank you for a swift response. 

Also, would you consider adding a slightly older version of rust to your CI? I've seen you are using `actions-rs/toolchain` so it might be as simple as adding a version to your build matrix.

**Comment by SanjoDeundiak** [comment]
@shssoichiro 1.77 & 1.78 doesn't compile as well

**Comment by shssoichiro** [comment]
In the meantime I've yanked 0.2.5 to prevent further updates. I'll be publishing a 0.2.6 as soon as #49 is merged

**Comment by SanjoDeundiak** [comment]
Ok, now it is, thank you :)

**Comment by shssoichiro** [comment]
Published new version 0.2.6. This one is validated to build against rustc 1.62.0 and newer.
